import { Nav } from '@/components/nav';
import { Footer } from '@/components/footer';
import { Button } from '@/components/button';
import { LiveScan } from '@/components/live-scan';
import { CodeBlock } from '@/components/code-block';
import { FeatureVisual } from '@/components/feature-visual';
import { ScrollReveal } from '@/components/scroll-reveal';
import { CipherText } from '@/components/cipher-text';
import { KonamiEgg } from '@/components/konami-egg';
import { MatrixRain } from '@/components/matrix-rain';
import Image from 'next/image';
import { ArrowRight } from 'lucide-react';

const headersCode = `// Generated by Barracade for Next.js
const securityHeaders = [
  {
    key: 'Content-Security-Policy',
    value: "default-src 'self'; script-src 'self'"
  },
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload'
  },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'X-Frame-Options', value: 'DENY' },
  {
    key: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin'
  },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=()'
  },
];

module.exports = {
  async headers() {
    return [{ source: '/(.*)', headers: securityHeaders }];
  },
};`;

export default function Page() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Barracade',
    applicationCategory: 'SecurityApplication',
    operatingSystem: 'Windows, macOS, Linux',
    description: 'Desktop security tool for apps and websites. Website scanning, RASP engine, static analysis, compliance reporting.',
    offers: {
      '@type': 'Offer',
      price: '69.99',
      priceCurrency: 'USD',
      availability: 'https://schema.org/InStock',
    },
    softwareVersion: '1.2',
    url: 'https://barracade.dev',
  };

  return (
    <>
      {/* barracade://initiate -- QlJDRC1TRUMtU1RBUlQ6IC9zZWN1cml0eS9sb2dzL2FyY2hpdmU= */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <Nav />
      <KonamiEgg />
      <main>

        {/* â”€â”€ Hero â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <section className="relative overflow-hidden pt-32 pb-20 lg:pt-40 lg:pb-28">
          <MatrixRain />
          <div className="absolute top-0 right-0 w-[55%] h-full hidden lg:block pointer-events-none">
            <div className="absolute inset-0 bg-gradient-to-r from-[#050505] via-[#050505]/80 to-[#050505]/20 z-10" />
            <div className="absolute inset-0 bg-gradient-to-t from-[#050505] via-transparent to-[#050505]/40 z-10" />
            <Image
              src="/image-removebg-preview (1).png"
              alt=""
              fill
              className="object-cover object-[50%_20%] invert opacity-[0.7] select-none"
              priority
            />
          </div>

          <div className="relative z-20 mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16">
            <div className="max-w-xl">
              <ScrollReveal delay={0.1}>
                <p className="text-[15.5px] text-neutral-400 leading-[1.75] max-w-lg">
                  Barracade is a desktop security tool for apps and websites
                  that were built fast and need to be locked down. It scans
                  your site for vulnerabilities, protects your app at runtime
                  against injection and traversal attacks, and analyzes your
                  source code for security issues before they ship.
                </p>
              </ScrollReveal>

              <ScrollReveal delay={0.15}>
                <p className="mt-4 text-[12px] text-neutral-600 font-mono">
                  Windows, macOS, Linux
                </p>
              </ScrollReveal>

              <ScrollReveal delay={0.2}>
                <div className="mt-8 flex gap-3">
                  <Button href="/purchase" size="md">
                    Download <ArrowRight className="h-3.5 w-3.5" />
                  </Button>
                  <Button href="/docs" variant="secondary" size="md">
                    Documentation
                  </Button>
                </div>
              </ScrollReveal>

              <div className="mt-16 opacity-30 hover:opacity-60 transition-opacity duration-1000">
                <CipherText
                  encrypted="746865206c6f677320726564206d656d626572"
                  decrypted="THE LOGS REMEMBER"
                  hint="Something is archived that shouldn't be"
                />
              </div>
            </div>
          </div>
        </section>

        {/* â”€â”€ Overview â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <section className="py-20">
          <div className="mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16">
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-x-10 gap-y-12">
              <ScrollReveal delay={0}>
                <div>
                  <h3 className="text-[13px] font-medium text-neutral-300 mb-2">Scanning</h3>
                  <p className="text-[13px] text-neutral-600 leading-relaxed">
                    Full security audits on any public URL. Headers, TLS, cookies,
                    exposed endpoints, CMS-specific issues. Letter grade A through F.
                  </p>
                </div>
              </ScrollReveal>
              <ScrollReveal delay={0.05}>
                <div>
                  <h3 className="text-[13px] font-medium text-neutral-300 mb-2">Protection</h3>
                  <p className="text-[13px] text-neutral-600 leading-relaxed">
                    Runtime application self-protection. Catches SQL injection, XSS,
                    SSRF, command injection, path traversal, and four more attack vectors.
                  </p>
                </div>
              </ScrollReveal>
              <ScrollReveal delay={0.1}>
                <div>
                  <h3 className="text-[13px] font-medium text-neutral-300 mb-2">Analysis</h3>
                  <p className="text-[13px] text-neutral-600 leading-relaxed">
                    Static analysis across JavaScript, TypeScript, Python, Go, Rust,
                    Java, C#, and PHP. Finds hardcoded secrets, injection risks, unsafe patterns.
                  </p>
                </div>
              </ScrollReveal>
              <ScrollReveal delay={0.15}>
                <div>
                  <h3 className="text-[13px] font-medium text-neutral-300 mb-2">Compliance</h3>
                  <p className="text-[13px] text-neutral-600 leading-relaxed">
                    Maps against SOC 2, PCI-DSS, HIPAA, and CIS. Tracks which controls
                    you meet, where the gaps are. Export audit-ready reports.
                  </p>
                </div>
              </ScrollReveal>
            </div>
          </div>
        </section>

        {/* â”€â”€ Scanner â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <section className="relative py-24 border-t border-white/[0.04]">
          <div className="absolute left-[10%] top-1/3 w-[400px] h-[400px] bg-emerald-500/[0.015] rounded-full blur-[100px] pointer-events-none" />
          <div className="hidden lg:block absolute right-10 top-12 pointer-events-none select-none">
            <div className="text-[9px] font-mono text-white/[0.04] leading-relaxed tracking-[0.25em] [writing-mode:vertical-lr]">6A09E667Â·BB67AE85Â·3C6EF372</div>
          </div>
          <div className="mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16">
            <div className="grid lg:grid-cols-[1fr,1.3fr] gap-16 items-start">
              <ScrollReveal>
                <div>
                  <h2 className="text-[15px] font-medium text-white mb-4">
                    Website scanning
                  </h2>
                  <p className="text-[13px] text-neutral-500 leading-[1.75] mb-4">
                    Point Barracade at any public URL and get a full security
                    audit in seconds. It resolves the target, negotiates TLS,
                    inspects every response header, checks cookie flags, probes
                    for exposed endpoints, and tests for platform-specific
                    vulnerabilities.
                  </p>
                  <p className="text-[13px] text-neutral-500 leading-[1.75] mb-4">
                    Results come back as a letter grade from A to F with a
                    prioritized list of findings. Each finding includes what was
                    checked, what failed, and how to fix it.
                  </p>
                  <p className="text-[13px] text-neutral-600 leading-[1.75]">
                    Supports batch scanning across multiple domains. Track grades
                    over time to catch regressions from deploys before your users do.
                  </p>
                </div>
              </ScrollReveal>
              <ScrollReveal delay={0.1}>
                <LiveScan />
              </ScrollReveal>
            </div>
          </div>
        </section>

        <div className="mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16 py-1">
          <div className="opacity-0 hover:opacity-40 transition-opacity duration-[2000ms] text-right">
            <CipherText
              encrypted="01101000 00110110 01100001 00110000 00111001 01100101 00110110 00110110 00110111"
              decrypted="THE RAIN CARRIES CONSTANTS"
              hint="Watch the falling characters closely"
            />
          </div>
        </div>

        {/* â”€â”€ Runtime Protection â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <section className="relative py-24 border-t border-white/[0.04]">
          <div className="absolute right-[8%] top-1/4 w-[350px] h-[350px] bg-emerald-500/[0.012] rounded-full blur-[80px] pointer-events-none" />
          <div className="hidden lg:block absolute left-6 bottom-20 pointer-events-none select-none">
            <div className="flex flex-col gap-1.5">
              <span className="text-[8px] font-mono text-emerald-900/20 tracking-[0.2em]">BLOCKED</span>
              <span className="text-[8px] font-mono text-white/[0.03] tracking-[0.2em]">4FÂ·A9Â·2CÂ·7E</span>
              <span className="text-[8px] font-mono text-white/[0.03] tracking-[0.2em]">1BÂ·83Â·D6Â·5F</span>
            </div>
          </div>
          <div className="mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16">
            <ScrollReveal>
              <h2 className="text-[15px] font-medium text-white mb-4">
                Runtime protection
              </h2>
              <p className="text-[13px] text-neutral-500 leading-[1.75] max-w-2xl mb-12">
                The RASP engine inspects every incoming request at the application
                layer. It parses payloads, query strings, headers, and body content
                against known attack signatures and behavioral heuristics. When a
                threat is identified, the request is blocked before it reaches your
                application code. Every decision is logged with full context.
              </p>
            </ScrollReveal>

            <div className="grid lg:grid-cols-2 gap-12">
              <ScrollReveal delay={0.05}>
                <div>
                  <h3 className="text-[12px] font-medium text-neutral-400 mb-6 tracking-wide uppercase">Attack vectors</h3>
                  <div className="space-y-0">
                    {[
                      { name: 'SQL Injection', desc: 'Detects query manipulation in parameters, headers, and body content' },
                      { name: 'Cross-Site Scripting', desc: 'Catches reflected and stored XSS payloads across any input' },
                      { name: 'Server-Side Request Forgery', desc: 'Blocks internal network access via user-controlled URLs' },
                      { name: 'Command Injection', desc: 'Prevents shell command execution through application inputs' },
                      { name: 'Path Traversal', desc: 'Stops directory escape attempts in file path parameters' },
                      { name: 'Prototype Pollution', desc: 'Detects __proto__ and constructor manipulation in JSON' },
                      { name: 'NoSQL Injection', desc: 'Catches operator injection in MongoDB and similar stores' },
                      { name: 'Header Injection', desc: 'Prevents CRLF injection and header splitting attacks' },
                      { name: 'Open Redirects', desc: 'Validates redirect targets against allowed domain lists' },
                    ].map((v) => (
                      <div key={v.name} className="flex items-start gap-3 py-2.5 border-b border-white/[0.03] last:border-0">
                        <span className="text-[10px] font-mono text-emerald-800 mt-0.5 shrink-0">{'>'}</span>
                        <div>
                          <span className="text-[12px] text-neutral-400">{v.name}</span>
                          <p className="text-[11px] text-neutral-700 mt-0.5">{v.desc}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </ScrollReveal>
              <ScrollReveal delay={0.1}>
                <FeatureVisual type="rasp" />
                <div className="mt-6">
                  <FeatureVisual type="defense" />
                </div>
              </ScrollReveal>
            </div>
          </div>
        </section>

        {/* â”€â”€ Headers Generator â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <section className="relative py-24 border-t border-white/[0.04]">
          <div className="absolute left-[5%] bottom-1/4 w-[300px] h-[300px] bg-emerald-500/[0.01] rounded-full blur-[80px] pointer-events-none" />
          <div className="hidden lg:block absolute right-8 bottom-16 pointer-events-none select-none">
            <div className="text-[8px] font-mono text-white/[0.035] tracking-[0.3em] leading-loose">
              CSPÂ·HSTSÂ·XFO<br/>CORPÂ·COEPÂ·COOP
            </div>
          </div>
          <div className="mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16">
            <div className="grid lg:grid-cols-[1.3fr,1fr] gap-16 items-start">
              <ScrollReveal>
                <CodeBlock code={headersCode} filename="next.config.js" />
              </ScrollReveal>
              <ScrollReveal delay={0.1}>
                <div>
                  <h2 className="text-[15px] font-medium text-white mb-4">
                    Security headers
                  </h2>
                  <p className="text-[13px] text-neutral-500 leading-[1.75] mb-4">
                    Select the headers you need and Barracade generates
                    deployment-ready configuration for your platform. Copy
                    the output straight into your project.
                  </p>
                  <div className="text-[12px] text-neutral-600 leading-[1.75] space-y-1.5 mb-6">
                    <p><span className="text-neutral-500">Headers:</span> CSP, HSTS, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy, CORS.</p>
                    <p><span className="text-neutral-500">Platforms:</span> Next.js, Vercel, Netlify, Express, Nginx, Apache, Caddy, Cloudflare.</p>
                  </div>

                  <div className="mt-8 opacity-20 hover:opacity-50 transition-opacity duration-1000">
                    <CipherText
                      encrypted="dGhyZXNob2xkIGF3YWl0cyBhIGtleQ=="
                      decrypted="A THRESHOLD AWAITS A KEY"
                      hint="You'll need more than a password"
                    />
                  </div>
                </div>
              </ScrollReveal>
            </div>
          </div>
        </section>

        {/* â”€â”€ Code Analysis â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <section className="relative py-24 border-t border-white/[0.04]">
          <div className="absolute right-[12%] top-1/3 w-[350px] h-[350px] bg-emerald-500/[0.012] rounded-full blur-[100px] pointer-events-none" />
          <div className="hidden lg:block absolute left-8 top-16 pointer-events-none select-none">
            <div className="text-[9px] font-mono text-white/[0.04] leading-relaxed tracking-[0.25em] [writing-mode:vertical-lr]">SASTÂ·CVEÂ·SBOMÂ·SARIF</div>
          </div>
          <div className="mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16">
            <div className="grid lg:grid-cols-[1fr,1.3fr] gap-16 items-start">
              <ScrollReveal>
                <div>
                  <h2 className="text-[15px] font-medium text-white mb-4">
                    Static analysis
                  </h2>
                  <p className="text-[13px] text-neutral-500 leading-[1.75] mb-4">
                    Scans your source code for security issues across JavaScript,
                    TypeScript, Python, Go, Rust, Java, C#, and PHP. Finds hardcoded
                    secrets, unsafe deserialization, injection patterns, insecure
                    cryptographic usage, and misconfigured permissions.
                  </p>
                  <p className="text-[13px] text-neutral-500 leading-[1.75] mb-4">
                    Results include file paths, line numbers, severity ratings, and
                    remediation guidance. Exportable as SARIF for CI/CD integration.
                  </p>
                  <h2 className="text-[15px] font-medium text-white mb-4 mt-12">
                    Dependency scanning
                  </h2>
                  <p className="text-[13px] text-neutral-500 leading-[1.75]">
                    Generates a software bill of materials from your dependency tree.
                    Cross-references against the NVD for known CVEs, flags typosquat
                    packages, and audits licenses for compliance conflicts.
                  </p>
                </div>
              </ScrollReveal>
              <ScrollReveal delay={0.1}>
                <FeatureVisual type="sast" />
                <div className="mt-6">
                  <FeatureVisual type="dependencies" />
                </div>
              </ScrollReveal>
            </div>
          </div>
        </section>

        {/* â”€â”€ Compliance â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <section className="relative py-24 border-t border-white/[0.04]">
          <div className="absolute left-[15%] top-1/2 -translate-y-1/2 w-[400px] h-[400px] bg-emerald-500/[0.015] rounded-full blur-[100px] pointer-events-none" />
          <div className="hidden lg:block absolute right-10 top-20 pointer-events-none select-none">
            <div className="flex flex-col gap-2">
              <span className="text-[8px] font-mono text-white/[0.04] tracking-[0.3em]">SOC2 â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘ 87%</span>
              <span className="text-[8px] font-mono text-white/[0.04] tracking-[0.3em]">PCI  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘ 92%</span>
              <span className="text-[8px] font-mono text-white/[0.04] tracking-[0.3em]">HIPA â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‘â–‘â–‘ 78%</span>
            </div>
          </div>
          <div className="mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16">
            <div className="grid lg:grid-cols-2 gap-16 items-start">
              <ScrollReveal>
                <FeatureVisual type="compliance" />
              </ScrollReveal>
              <ScrollReveal delay={0.1}>
                <div>
                  <h2 className="text-[15px] font-medium text-white mb-4">
                    Compliance mapping
                  </h2>
                  <p className="text-[13px] text-neutral-500 leading-[1.75] mb-4">
                    Barracade maps your scan results, RASP configuration, code
                    analysis findings, and dependency status against four frameworks:
                    SOC 2, PCI-DSS, HIPAA, and CIS Benchmarks.
                  </p>
                  <p className="text-[13px] text-neutral-500 leading-[1.75] mb-4">
                    For each framework, you see which controls are met, which are
                    partially met, and which have gaps. Track remediation progress
                    over time and export audit-ready PDF reports.
                  </p>
                  <p className="text-[13px] text-neutral-600 leading-[1.75]">
                    Coverage data updates automatically as findings are resolved.
                    No manual mapping required.
                  </p>
                </div>
              </ScrollReveal>
            </div>
          </div>
        </section>

        {/* Puzzle breadcrumbs */}
        <div className="mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16 py-2 flex justify-between">
          <div className="opacity-0 hover:opacity-30 transition-opacity duration-[3000ms]">
            <CipherText
              encrypted="Uif!cbssjfs!qspufdut"
              decrypted="THE BARRIER PROTECTS"
              hint="Shifted by one â€” what stands between you and access?"
            />
          </div>
          <div className="opacity-0 hover:opacity-30 transition-opacity duration-[3000ms]">
            <CipherText
              encrypted="36 61 30 39 65 36 36 37"
              decrypted="6A09E667"
              hint="First word of a familiar hash"
            />
          </div>
          <div className="opacity-0 hover:opacity-30 transition-opacity duration-[3000ms]">
            <CipherText
              encrypted="%2f%62%61%72%72%61%63%61%64%65"
              decrypted="/barracade/..."
              hint="Paths hide in plain sight"
            />
          </div>
        </div>

        {/* â”€â”€ Pricing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */}
        <section className="py-16 border-t border-white/[0.04]">
          <div className="mx-auto max-w-[1600px] px-6 lg:px-12 xl:px-16">
            <ScrollReveal>
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-6">
                <div>
                  <p className="text-[14px] text-neutral-300">$69.99, one-time</p>
                  <p className="text-[12px] text-neutral-600 mt-1">
                    Lifetime license. All platforms. Every future update included.
                  </p>
                </div>
                <Button href="/purchase" size="md">
                  Download <ArrowRight className="h-3.5 w-3.5" />
                </Button>
              </div>
            </ScrollReveal>
          </div>
        </section>

      </main>
      <Footer />
    </>
  );
}
