import { Nav } from '@/components/nav';
import { Footer } from '@/components/footer';
import { ScrollReveal } from '@/components/scroll-reveal';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy - Barracade',
  description: 'How Barracade collects, uses, and protects your personal information.',
};

const EFFECTIVE_DATE = 'March 26, 2026';
const CONTACT_EMAIL = 'security@barracade.com';

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <main className="pt-32 pb-20">
        <div className="mx-auto max-w-3xl px-6">
          <ScrollReveal>
            <h1 className="text-2xl font-medium tracking-tight text-white">Privacy Policy</h1>
            <p className="mt-2 text-[12px] font-mono text-neutral-700">Effective {EFFECTIVE_DATE}</p>
          </ScrollReveal>

          <div className="mt-12 space-y-12 text-[14px] text-neutral-500 leading-[1.8]">

            <ScrollReveal>
              <section>
                <p>
                  Barracade is a desktop security application. This policy explains what
                  information we collect when you use barracade.dev or the Barracade desktop
                  app, how we use it, and what rights you have.
                </p>
              </section>
            </ScrollReveal>

            <ScrollReveal>
              <section>
                <h2 className="text-[14px] font-medium text-neutral-300 mb-4">1. Information we collect</h2>
                <div className="space-y-4">
                  <div>
                    <p className="text-neutral-400 mb-2">Account information</p>
                    <p>
                      When you create an account, we collect your email address and an optional
                      name. Your password is hashed with bcrypt before storage. We never store
                      your password in plain text.
                    </p>
                  </div>
                  <div>
                    <p className="text-neutral-400 mb-2">Payment information</p>
                    <p>
                      Payments are processed by Stripe. We do not receive or store your credit
                      card number, CVV, or banking details. Stripe transmits a confirmation of
                      payment completion, which we use to activate your license. Your payment
                      details are governed by{' '}
                      <a
                        href="https://stripe.com/privacy"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-neutral-400 hover:text-white underline underline-offset-2 transition-colors"
                      >
                        Stripe's Privacy Policy
                      </a>.
                    </p>
                  </div>
                  <div>
                    <p className="text-neutral-400 mb-2">License and purchase data</p>
                    <p>
                      We store your license key, purchase date, and licensed email address.
                      This is required to validate your license when you activate the desktop app.
                    </p>
                  </div>
                  <div>
                    <p className="text-neutral-400 mb-2">Usage data</p>
                    <p>
                      We use Vercel Analytics and Speed Insights to collect anonymous,
                      aggregated page view and performance data. This data does not include
                      personally identifiable information and is used to improve the website.
                    </p>
                  </div>
                  <div>
                    <p className="text-neutral-400 mb-2">Scan data</p>
                    <p>
                      All security scans, analyses, and reports generated by the Barracade
                      desktop app run locally on your machine. Scan results are not transmitted
                      to our servers.
                    </p>
                  </div>
                </div>
              </section>
            </ScrollReveal>

            <ScrollReveal>
              <section>
                <h2 className="text-[14px] font-medium text-neutral-300 mb-4">2. How we use your information</h2>
                <ul className="space-y-2">
                  <li>To create and manage your account</li>
                  <li>To issue and validate your software license</li>
                  <li>To process your payment through Stripe</li>
                  <li>To send transactional emails (purchase confirmation, license delivery)</li>
                  <li>To respond to support inquiries</li>
                  <li>To detect and prevent fraud and abuse</li>
                </ul>
                <p className="mt-4">
                  We do not sell your data. We do not use your information for advertising.
                  We do not share your information with third parties except as described below.
                </p>
              </section>
            </ScrollReveal>

            <ScrollReveal>
              <section>
                <h2 className="text-[14px] font-medium text-neutral-300 mb-4">3. Third-party services</h2>
                <div className="space-y-3">
                  <div className="grid sm:grid-cols-[140px,1fr] gap-2 border-b border-white/[0.04] pb-3">
                    <span className="text-neutral-400">Stripe</span>
                    <span>Payment processing. Subject to Stripe's privacy policy.</span>
                  </div>
                  <div className="grid sm:grid-cols-[140px,1fr] gap-2 border-b border-white/[0.04] pb-3">
                    <span className="text-neutral-400">Vercel</span>
                    <span>Hosting and analytics. Vercel may log request metadata (IP, user agent) in accordance with their data processing agreement.</span>
                  </div>
                  <div className="grid sm:grid-cols-[140px,1fr] gap-2">
                    <span className="text-neutral-400">No others</span>
                    <span>We do not use advertising networks, marketing platforms, or data brokers.</span>
                  </div>
                </div>
              </section>
            </ScrollReveal>

            <ScrollReveal>
              <section>
                <h2 className="text-[14px] font-medium text-neutral-300 mb-4">4. Data retention</h2>
                <p>
                  Your account and license data are retained for as long as your account
                  exists. If you request account deletion, we remove your personal data
                  within 30 days, subject to our obligation to retain certain records for
                  legal and accounting purposes (typically 7 years for payment records).
                </p>
              </section>
            </ScrollReveal>

            <ScrollReveal>
              <section>
                <h2 className="text-[14px] font-medium text-neutral-300 mb-4">5. Security</h2>
                <p>
                  Passwords are hashed with bcrypt (cost factor 12). All communication
                  with barracade.dev uses TLS. Access to account data is restricted to
                  authenticated sessions. We do not store payment card data on our servers.
                </p>
              </section>
            </ScrollReveal>

            <ScrollReveal>
              <section>
                <h2 className="text-[14px] font-medium text-neutral-300 mb-4">6. Your rights</h2>
                <p className="mb-3">
                  Depending on where you reside, you may have rights to:
                </p>
                <ul className="space-y-2">
                  <li>Access the personal data we hold about you</li>
                  <li>Request correction of inaccurate data</li>
                  <li>Request deletion of your account and personal data</li>
                  <li>Request a copy of your data in a portable format</li>
                  <li>Object to certain processing</li>
                </ul>
                <p className="mt-4">
                  To exercise these rights, email{' '}
                  <a
                    href={`mailto:${CONTACT_EMAIL}`}
                    className="text-neutral-400 hover:text-white underline underline-offset-2 transition-colors"
                  >
                    {CONTACT_EMAIL}
                  </a>.
                </p>
              </section>
            </ScrollReveal>

            <ScrollReveal>
              <section>
                <h2 className="text-[14px] font-medium text-neutral-300 mb-4">7. Cookies</h2>
                <p>
                  We use a single session cookie set by NextAuth to keep you signed in.
                  This cookie is strictly necessary for authentication and is not used for
                  tracking. It expires when your session ends or after 30 days. We do not
                  use advertising or analytics cookies.
                </p>
              </section>
            </ScrollReveal>

            <ScrollReveal>
              <section>
                <h2 className="text-[14px] font-medium text-neutral-300 mb-4">8. Changes to this policy</h2>
                <p>
                  We may update this policy from time to time. We will post the new policy
                  here with an updated effective date. Continued use of Barracade after
                  changes take effect constitutes acceptance of the updated policy.
                </p>
              </section>
            </ScrollReveal>

            <ScrollReveal>
              <section>
                <h2 className="text-[14px] font-medium text-neutral-300 mb-4">9. Contact</h2>
                <p>
                  Questions about this policy or your data can be sent to{' '}
                  <a
                    href={`mailto:${CONTACT_EMAIL}`}
                    className="text-neutral-400 hover:text-white underline underline-offset-2 transition-colors"
                  >
                    {CONTACT_EMAIL}
                  </a>.
                </p>
              </section>
            </ScrollReveal>

          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
